### ISSUE TITLE
Cannot read property "startLoadWithResult" of null in Expo 49

### ISSUE THREAD

**Issue by AlexHayton** [announcekitapp/announcekit-react-native#4]
The library is not working in Expo 49 / RN 0.72.3.

![IMG_1443](https://github.com/announcekitapp/announcekit-react-native/assets/63102/73d2449c-e740-4c6f-865e-3f66e6dbc488)

Reproduction steps:
Call `useWidget`

**Comment by eslamelkholy** [comment]
hi @AlexHayton thanks for reporting this issue this one is due to you have to versions of webview we have published an update to our package at version 2.0.2 to fix this issue , please update yours and must be fixed

**Comment by AlexHayton** [comment]
Thanks!
